Main svc
gray-alt/java-explore-with-me pull request #7
Opened 2023-09-07 15:07 UTC by gray-alt

2023-09-08 12:30 UTC, EugeneLenkevich requested changes
Привет, Сергей! Спасибо за PR.

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-08 12:30 UTC, EugeneLenkevich commented on ewm-svc/src/main/java/ru/practicum/category/service/CategoryServiceImpl.java
> +@AllArgsConstructor
@AllArgsConstructor

Давай все таки тут поставим @RequiredArgsConstructor
Иначе, если добавим допустим строковое поле, например, с настройкой, он будет пытаться запихать эту строку в конструктор, не удобно :)

2023-09-11 06:18 UTC, gray-alt commented on ewm-svc/src/main/java/ru/practicum/controller/AdminController.java
> +        log.info("Admin create user: " + userDto.toString());
Я эти логи добавил, чтобы разобраться, а что вообще из Постмана приходит. Там же у всех тестов есть Pre-request script, который в итоге собирает и сам запрос, и его тело. И в Постмане у меня не получилось посмотреть, какое тело ушло-то, вкладка Request почему-то пустая у меня была. А таким образом удалось удавалось посмотреть, что пришло на вход.

2023-09-11 06:32 UTC, EugeneLenkevich commented on ewm-svc/src/main/java/ru/practicum/controller/AdminController.java
> +        log.info("Admin create user: " + userDto.toString());
Как бы такой момент. В целом это все понятно, но тут такой момент - никто же не в курсе что это отладочная информация, а потом, в реальном проекте, эта отладочная информация может попасть в ПРОД, можно по шапке получить (например если залогируем сенситивную информацию), в общем с этим надо поаккуратней :)

2023-09-11 06:36 UTC, gray-alt commented on ewm-svc/src/main/java/ru/practicum/controller/AdminController.java
> +        log.info("Admin create user: " + userDto.toString());
Понял спасибо ))

2023-09-11 07:21 UTC, merged